### ISSUE TITLE
v0.2.2: Undefined rule "media-feature-parentheses-space-inside"

### ISSUE THREAD

**Issue by rox163** [billybonks/ember-cli-stylelint#14]
Running `ember s` gives me this undefined rule error.
package.json - 
```
 "ember-cli-stylelint": "0.2.2",
"stylelint": "^7.0.3",
"stylelint-config-standard": "^11.0.0"
```

Moving back to stylelint: 6.8.0 and stylelint-config-standard:10.0.0 fixes the issue. I'm guessing this addon just needs an update to its dependencies.

Thanks.

**Comment by billybonks** [comment]
updated to latest use 0.5.0 thanks

**Comment by billybonks** [comment]
hi @rox163  i will be closing this issue, since it has been resolved if it still doesn't work for you after upgrade feel free to reopen it
