### ISSUE TITLE
[3.0.0] path should be a `path.relative()`d string, but got "/home/boris/project/app/index.html"

### ISSUE THREAD

**Issue by boris-petrov** [billybonks/ember-cli-stylelint#213]
I updated to 3.0.0 and I get this error when I run `ember server`. It works fine on 2.2.0. I have no config in `ember-cli-build` - i.e. everything is default.

Any ideas?

**Comment by billybonks** [comment]
👋 Sorry for the trouble, works with add-ons but broke with apps, will have to build a regression test for this. will publish a fix soon @rwwagner90

**Comment by boris-petrov** [comment]
@billybonks - with the new version of `broccoli-stylelint` it works fine, thank you! I'll leave you to close the issue when you please. Thanks again!

**Comment by billybonks** [comment]
👍  3.1.0 is fixed, also thanks to @rwwagner90 for helping :).

**Comment by rwwagner90** [comment]
@billybonks I now am back to my original issue `Cannot set property 'errored' of undefined`
