### ISSUE TITLE
Warnings not showing

### ISSUE THREAD

**Issue by amk221** [billybonks/ember-cli-stylelint#24]
My editor (Atom) is correctly showing me linting warnings (like indentation) picked up from `.stylelintrc`. But ember-cli-stylelint is not reporting them.

I had a small dig, and I think it's something to do with the level being `warning` rather than `error`.

**Comment by billybonks** [comment]
<img width="670" alt="screen shot 2016-09-06 at 5 15 19 am" src="https://cloud.githubusercontent.com/assets/1640136/18265742/82141388-7417-11e6-8d75-c1449ca9c117.png">

It seems to be working on my app, could you share some more information.

the level `warning` means don't complain if it's only a warning this should be configurable though.

**Comment by amk221** [comment]
Ok :)

I'm still really struggling with ember-cli-stylelint. I've set up a fresh ember-cli project, installed ember-cli-stylelint, and ember-cli-sass.

Then I added logging to broccoli-stylelint to see what was happening.

![artboard 1](https://cloud.githubusercontent.com/assets/382061/18267262/2b99a5d2-7416-11e6-9027-efd3eadbbf9f.png)

**Comment by billybonks** [comment]
thanks, ill be looking at this in the morning. sorry for the problems you have faced this far. the next release fixes pod styles, and irons out a few more things. ill release tomorrow 👍

**Comment by amk221** [comment]
No need to apologise!

**Comment by billybonks** [comment]
:) thanks. try 0.5.0 i just published

**Comment by amk221** [comment]
Thanks
