### ISSUE TITLE
CSS Syntax

### ISSUE THREAD

**Issue by leifdejong** [billybonks/ember-cli-stylelint#34]
@billybonks having an issue when setting syntax to `css`, stylelint fails claiming its an invalid syntax. Dug into the [stylelint source code](https://github.com/stylelint/stylelint/blob/cafcefa4e6b2602b413861c73d62ded3737d2eb1/src/standalone.js#L157) and sure enough, they are not checking against it. My case is that I am using `postcss-cssnext` and need stylelint to lint through the `app.css` file. Any ideas?

**Comment by billybonks** [comment]
What property is invalid.
I presume you mean that you searched the stylelint code to see if it supports your property?

**Comment by billybonks** [comment]
@leifdejong 

hey it was a bug in my code, fixed it

here is example config for css, upgrade to 0.6.3
```
var app = new EmberApp(defaults, {
  stylelint: {
    linterConfig:{
      syntax: 'css'
    },
  }
});
```

**Comment by leifdejong** [comment]
@billybonks you're the man! Fixed my issues! Thank you
