### ISSUE TITLE
Addon Linting

### ISSUE THREAD

**Issue by leifdejong** [billybonks/ember-cli-stylelint#41]
Hi! Been trying to get linting setup in an addon and not getting any warnings while running `ember s` when developing the addon. Any way to do this? Installed `ember-cli-sass`, `ember-cli-stylelint`, and `stylelint-config-standard`.

```
stylelint: {
      linterConfig: {
        syntax: 'scss',
        configFile: '.stylelintrc',
      },
    },
```

```
{
  "extends": "stylelint-config-standard",
  "rules": {
    "selector-type-no-unknown": null,
  }
}
```

**Comment by leifdejong** [comment]
After investigating a little further, if I change:

```
// index.js
return new StyleLinter(this.app.trees.app, this.styleLintOptions);
```
to
```
// where my styles are located
return new StyleLinter('app/styles', this.styleLintOptions);
```

everything starts working. Thought about putting in an option for path but then those options get passed along to the consuming app so no good. What do you think?

**Comment by billybonks** [comment]
ye, i added `return new StyleLinter(this.app.trees.app, this.styleLintOptions);` to support https://github.com/billybonks/ember-cli-stylelint/issues/3. but ever since then i have been meaning to add an option `podStyles`

```
podstyles = true //this.app.trees.app
podstyles = false //this.app.trees.styles
```

i noticed you used `'app/styles'` i think `this.app.trees.styles` should work as well. i very much welcome a pr to solve this 👍

**Comment by leifdejong** [comment]
@billybonks this would be a local addon option?

**Comment by leifdejong** [comment]
@billybonks have an issue with `this.app.trees.styles` as it points to `tests/dummy/app/styles` instead of `app/styles`. Tried to change the config path but with no luck. Maybe one of the better options would be to do what [ember-cli-sass](https://github.com/aexmachina/ember-cli-sass) does with `includePaths` and their [addon docs](https://github.com/aexmachina/ember-cli-sass#addon-usage). This would allow the user to specify where to lint from. Thoughts...?

**Comment by billybonks** [comment]
hey, sorry for the delay, this makes sense to me. i think in the future it would be nice to set a mode, like `mode:pod` or mode:addon` but this would be an extension of your work here :).

**Comment by billybonks** [comment]
or

```
stylelint: {
    linterConfig:{
      syntax: 'less',
      podstyles: true,
      includePaths: [
         "x/y/z"
     ]
    },
  }
```

**Comment by billybonks** [comment]
```
stylelint: {
    linterConfig:{
      syntax: 'less',
      includePaths: [
         "x/y/z"
     ]
    },
  }
```

**Comment by leifdejong** [comment]
awesome. will work on it this weekend and submit a PR

**Comment by billybonks** [comment]
awesome :D!

**Comment by jamesarosen** [comment]
I pushed #44 as a first go.
