### ISSUE TITLE
Incompatible with QUnit 2.x

### ISSUE THREAD

**Issue by jamesarosen** [billybonks/ember-cli-stylelint#45]
Running an app or addon with this and QUnit 2.x causes the following error:
```
not ok 7 PhantomJS 2.1 - TestLoader Failures: app/styles/app.stylelint-test: could not be loaded
    ---
        actual: >
            null
        stack: >
            http://localhost:7357/assets/test-support.js:4381:133
            http://localhost:7357/assets/tests.js:294:9
            exports@http://localhost:7357/assets/vendor.js:132:37
            requireModule@http://localhost:7357/assets/vendor.js:32:25
            require@http://localhost:7357/assets/test-support.js:7104:14
            loadModules@http://localhost:7357/assets/test-support.js:7096:21
            load@http://localhost:7357/assets/test-support.js:7126:33
            http://localhost:7357/assets/test-support.js:7009:22
        message: >
            Died on test #1 moduleLoadFailure@http://localhost:7357/assets/test-support.js:6997:17
            require@http://localhost:7357/assets/test-support.js:7106:29
            loadModules@http://localhost:7357/assets/test-support.js:7096:21
            load@http://localhost:7357/assets/test-support.js:7126:33
            http://localhost:7357/assets/test-support.js:7009:22: The global `module` is removed in QUnit 2.0.
            Details in our upgrade guide at https://qunitjs.com/upgrade-guide-2.x/
        Log: |
    ...
```
I get QUnit 2.x via `"ember-cli-qunit": "^3.0.1"`, which is the default for ember-cli 2.10.0.

This was opened at https://github.com/ember-cli/ember-cli-qunit/issues/158, but they said the problem was with ember-cli-sass-lint.

I don't know where the right place to fix this is.

**Comment by jamesarosen** [comment]
The problem is in [broccoli-stylelint](https://github.com/billybonks/broccoli-stylelint/blob/0.8.3/index.js#L198-L213).

This project both [uses the `generateTestFile` API](https://github.com/billybonks/ember-cli-stylelint/blob/7396ef0f322a1682ff39b7d9c3cac9c9059dcf45/index.js#L32-L53) and [builds a tree with broccoli-stylelint](https://github.com/billybonks/ember-cli-stylelint/blob/7396ef0f322a1682ff39b7d9c3cac9c9059dcf45/index.js#L60-L62). That latter tree adds QUnit 1.x tests to the test suite.

For now, I'll set `generateTests: false`, though that means I won't get a failing build when linting fails.

**Comment by jamesarosen** [comment]
Ohhhh! The problem is that [ember-cli-stylelint reuses the same `styleLintOptions` object](https://github.com/billybonks/ember-cli-stylelint/blob/7396ef0f322a1682ff39b7d9c3cac9c9059dcf45/index.js#L61) for each tree, but [broccoli-stylelint deletes all the properties of that object](https://github.com/billybonks/broccoli-stylelint/blob/17b8790f0388b0635f1967c4578187b82af4e4c0/index.js#L63).

I'll have a patch up shortly.

**Comment by billybonks** [comment]
OOOOOH. i was unable to reproduce with `ember-cli-qunit@3.0.2` but that is because i only had one path

**Comment by billybonks** [comment]
@jamesarosen can you try this by targeting `billybonks/ember-cli-stylelint#master` in your package.json. before i publish the next version 👍

**Comment by jamesarosen** [comment]
`cb8278e9` (current master) works great! :shipit:
