### ISSUE TITLE
Unable to make includePaths to work

### ISSUE THREAD

**Issue by mikkopaderes** [billybonks/ember-cli-stylelint#48]
So far I'm unable to make `includePaths` to work in addons. It only lints the first path which is `this.app.trees.app`.

If I replace `var toBeLinted = [ this.app.trees.app ];` with `var toBeLinted = [ 'addon/styles', this.app.trees.app ];`, it will lint *addon/styles* but not `this.app.trees.app`.

Are there any extra configurations needed to make it work on multiple paths?

Here's the tools I'm using:
* Ember v2.8.3 for my addon
* ember-cli-stylelint v0.9.0
* stylelint-config-standard v14.0.0

**Comment by billybonks** [comment]
![image](https://cloud.githubusercontent.com/assets/1640136/21536285/d58d722c-cdbb-11e6-84c7-2c0ea0e676a9.png)

in the `ember-cli-stylelint/index.js` i log toBeLinted

![image](https://cloud.githubusercontent.com/assets/1640136/21536295/f428894c-cdbb-11e6-9726-ac5244877a5c.png)

my config 

```
    stylelint: {
      linterConfig:{
        syntax: 'scss'
      },
      includePaths: [ 'addon/styles', 'app/styles' ]
    }
```

if your files are extension `sass`, the scss language won't parse them

**Comment by rmmmp** [comment]
That's weird. I'm still unable to make it work unless I remove `this.app.trees.app` in `toBeLinted` array.

I'm using plain CSS. Here's my config:

```javascript
var app = new EmberAddon(defaults, {
  // Add options here
  stylelint: {
    linterConfig:{
      syntax: 'css'
    },
    includePaths: ['addon/styles']
  }
});
```

**Comment by bruceblay** [comment]
this worked for me

![screenshot 2017-03-07 17 14 25](https://cloud.githubusercontent.com/assets/1952514/23682551/fb795c16-0359-11e7-8dc3-4900d4a06212.png)

my config since I have a lot of in repo addons:

```
styleLint: {
      linterConfig:{
        syntax: 'scss'
      },
      includePaths: addonDirs
        .map((dirname) => `lib/${dirname}/addon/styles`)
        .filter((dirname) => dirExists(Path.join(__dirname, dirname)))
    }
```

**Comment by billybonks** [comment]
thanks, i will test this again with one of my addons

**Comment by billybonks** [comment]
@rmmmp is this a public repo ?

**Comment by bruceblay** [comment]
Come to think of it, I had to remove this.app.trees.app from the toBeLinted array before it would push new includedPaths.

**Comment by billybonks** [comment]
I think I may know what the issue is. I would appreciate it if you could
install the package pointing at master to see if it works.

**Comment by billybonks** [comment]
published 0.13.0 let me know if this fixes the problem 👍

**Comment by rmmmp** [comment]
@billybonks, sorry for the late response. Unfortunately the latest version (14.0) still doesn't solve the issue. It still only lints the first element in `toBeLinted` variable.

**Comment by billybonks** [comment]
@rmmmp is your project open source ? or would you be able to recreate the
issue in an open source example ?

**Comment by rmmmp** [comment]
@billybonks, not open source. I'll just try to recreate the issue in open source. I'll post back when I got it up.

**Comment by billybonks** [comment]
thanks a million :)

**Comment by rmmmp** [comment]
@billybonks, [here's](https://github.com/rmmmp/stylelint-test) the replication. It's just a new addon from scratch.

What I'm expecting is that it should lint the `addon.css` inside `addon/styles` as I've configured it in the `ember-cli-build.js`. Unfortunately, that's not happening. It only happens when I remove `this.app.trees.app` inside the `toBeLinted` variable.

**Comment by billybonks** [comment]
this is perfect thanks 👍  let you know when i find something

**Comment by dfalling** [comment]
Has there been any progress on this ticket?  I'm happy to throw some time at it if someone can point me to a place to start.

**Comment by billybonks** [comment]
@dfalling sorry for the ultra late reply but there has not.

but there has been progress on included paths in general. that configuration is basically a hack `workaround`. hoping to get some changes done to ember-cli and deprecate the config all together.

but i would like to know what kind's of paths you are all including. so i can make an informed decision, and make sure i don't miss edge cases.

https://github.com/billybonks/ember-cli-stylelint/issues/73#issuecomment-377518090
