### ISSUE TITLE
Run

### ISSUE THREAD

**Issue by knownasilya** [billybonks/ember-cli-stylelint#5]
How do I run this? I get no output from `ember build` or `ember test`.. I have a `.stylelintrc` and added `postcss-less` to processors:

```json
{
  "processors": ["postcss-less"],
  "rules": {
    "color-no-invalid-hex": true,
    "declaration-colon-space-after": "always",
    "indentation": [2, {
      "except": ["value"]
    }],
    "max-empty-lines": 2,
    "rule-nested-empty-line-before": [ "always", {
      "except": ["first-nested"],
      "ignore": ["after-comment"]
    }]
  }
}
```

**Comment by billybonks** [comment]
hey sorry there was a bug, it wasn't printing to console. i added a test so that this doesn't happen again. grab the latest release 0.2.2

**Comment by knownasilya** [comment]
Will give it a go again, thanks :)

**Comment by billybonks** [comment]
@knownasilya is it working ?

**Comment by knownasilya** [comment]
No, it has the same result, no output. I'll try to create a fresh project and test on that.

**Comment by billybonks** [comment]
Hi @knownasilya  sorry for late reply i have been offline on holiday. have you had any success. it might be because of `postcss-less` processor will test it.

**Comment by billybonks** [comment]
Hi @knownasilya please upgrade to 0.6.0 and change your `ember-cli-build.js` file to reflect the syntax of your choosing

here is a sample
```javascript
var EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    stylelint: {
      linterConfig:{
        syntax: 'less'
      }
    }
  });
```

**Comment by knownasilya** [comment]
Works 👍
