### ISSUE TITLE
Undefined rule font-family-no-duplicate-names

### ISSUE THREAD

**Issue by taylon** [billybonks/ember-cli-stylelint#50]
A new rule was introduced in Stylelint 7.6 and now this addon is returning the following error:

Undefined rule font-family-no-duplicate-names

By trying to pull request the fix I saw that Stylelint was already updated on broccoli-stylelint. Only a release bump for both ember-cli-stylelint and broccoli-stylelint should fix it.

Thanks,

**Comment by leifdejong** [comment]
@billybonks do you know the status on this issue. Having problems with it

**Comment by billybonks** [comment]
ill update it today thanks 👍

**Comment by billybonks** [comment]
Hey it seems 0.9.0 the correct version I'll test on my project today. And make sure it is fixed :)

**Comment by billybonks** [comment]
ok bumped versions tested should be good now :) thanks.

**Comment by taylon** [comment]
We need a version bump here as well right? With the new version of broccoli-stylelint =D

**Comment by billybonks** [comment]
*0.9.1* has been published for a while :). i pushed the changes upstream.

**Comment by billybonks** [comment]
@taylon @leifdejong is this working for you ?

**Comment by taylon** [comment]
Yeah it works. I'm closing the issue.

Thanks,
