### ISSUE TITLE
improve blueprint

### ISSUE THREAD

**Issue by billybonks** [billybonks/ember-cli-stylelint#57]
Currently i have just pasted stylelint-config-standard. would like a way to include it like this:
https://github.com/billybonks/ember-cli-stylelint/commit/4a7fa6a073075002da3253aaae4fc4819130bfe4

I didn't do it that way, because the package needs to be installed as a dependency of the app vs nested within node_modules of the package.

**Comment by knownasilya** [comment]
Good example: https://github.com/plusacht/ember-bootstrap-datetimepicker/blob/master/blueprints/ember-bootstrap-datetimepicker/index.js#L4

**Comment by billybonks** [comment]
thanks @knownasilya that was a big help :)
