### ISSUE TITLE
This does not seam to work with the ember-cli beta

### ISSUE THREAD

**Issue by ssylvia** [billybonks/ember-cli-stylelint#63]
Using ember-cli 12.13.0 beta 2.

When I run `ember test` I get errors like:

```sh
Unexpected token 'const' at http://localhost:7357/assets/tests.js
```

Ember cli beta changed updated to babel 6 which may have broke the build.

**Comment by billybonks** [comment]
this seems to be related to https://github.com/billybonks/ember-cli-stylelint/issues/68 will be looking into it. sorry for the delay, and thank you for brining it up early. will be sure to respond faster :)
