### ISSUE TITLE
Project cannot be built when using Ember-CLI 2.13

### ISSUE THREAD

**Issue by boris-petrov** [billybonks/ember-cli-stylelint#65]
Please see this issue: https://github.com/ember-cli/ember-cli/issues/7006.

Short version: when using:

```javascript
minifyJS: {
  enabled: true
}
```

In `ember-cli-build.js` and `ember-cli-stylelint` is in `package.json`, the project cannot be built in any environment other than `production`. The error is:

```
cleaning up...                                                                                                                                               
Build failed.                                                                                                                                                
File: assets/frontend.js (8749:8)                                                                                                                            
The Broccoli Plugin: [UglifyWriter] failed with:                                                                                                             
SyntaxError: The Broccoli Plugin: [UglifyWriter] failed with:                                                                                                
  at JS_Parse_Error.get (<anonymous>:86:23)
  ...
```

**Comment by boris-petrov** [comment]
For anyone who is watching this (and mostly the maintainers of `ember-cli-stylelint`), here is a branch that someone made:

https://github.com/pgrippi/ember-cli-stylelint/tree/ember-cli-2.13

That works with `Ember CLI 2.13`. Should be easy enough to copy-paste it or @pgrippi could create a pull request for you to simply merge.

**Comment by eshtadc** [comment]
Looks like https://github.com/billybonks/ember-cli-stylelint/commit/7e456537f3bfaba26ddc6f3079a8d4cd13e27566 resolved this issue.
