### ISSUE TITLE
PhantomJS 2.1 - Global error: SyntaxError: Use of reserved word 'let' in strict mode

### ISSUE THREAD

**Issue by kgish** [billybonks/ember-cli-stylelint#68]
Installed `ember-cli-stylelint` and get the following error when I run build or test:

```
not ok 1 PhantomJS 2.1 - Global error: SyntaxError: Use of reserved word 'let' in strict mode at http://localhost:7357/assets/tests.js, line 20
```
Version:
```
$ ember -v
ember-cli: 2.13.1
node: 6.9.5
os: linux x64
```
File package.json:
```
 "devDependencies": {
    "broccoli-asset-rev": "^2.4.5",
    "ember-ajax": "^3.0.0",
    "ember-cli": "2.13.1",
    "ember-cli-app-version": "^3.0.0",
    "ember-cli-babel": "^6.0.0",
    "ember-cli-dependency-checker": "^1.3.0",
    "ember-cli-dotenv": "^1.2.0",
    "ember-cli-eslint": "^3.0.0",
    "ember-cli-htmlbars": "^1.1.1",
    "ember-cli-htmlbars-inline-precompile": "^0.4.0",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-qunit": "^4.0.0",
    "ember-cli-sass": "^6.1.3",
    "ember-cli-shims": "^1.1.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.13.0",
    "ember-data-github": "^0.3.1",
    "ember-export-application-global": "^2.0.0",
    "ember-font-awesome": "^3.0.5",
    "ember-load-initializers": "^1.0.0",
    "ember-resolver": "^4.0.0",
    "ember-source": "~2.13.0",
    "ember-truth-helpers": "^1.3.0",
    "emberx-select": "^3.0.1",
    "loader.js": "^4.2.3"
  }
```

**Comment by steveszc** [comment]
I got a similar error when running my test suite on Phantomjs 2.1. Without ember-cli-stylelint my tests run fine, with ember-cli-stylelint installed (0.14.0) I get a similar syntax error (due to ES2015 syntax) from assets/tests.js. Seems like this addon is preventing the tests.js file from being transpiled by Babel. (I'm using ember-cli 2.13.2).

**Comment by raspo** [comment]
I get a similar error after installing `babel-plugin-transform-object-rest-spread`.
The build breaks complaining about the "unexpected" `...` syntax. If I then remove `ember-cli-stylelint` (v 0.14.00) from my `package.json`, everything works fine.

**Comment by billybonks** [comment]
i have been able to reproduce the issue, will fix it asap. sorry for the delay i have been swamped
